### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by jonchristmas** [qazbnm456/VWGen#2]
I followed the instructions and I am running Ubuntu 16.04.03

This is the error:
root@webserver:/home/user/VWGen-master# ./VWGen.py
[INFO] Loading modules:
[INFO] 	 mod_unfilter, mod_expand, mod_sqli, mod_nosqli, mod_lfi, mod_crlf, mod_exec, mod_xss
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/api.py", line 200, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

I tried to install python-watchdog through apt to see if that solved the problem and it ran once but didnt finish starting it up on the second attempt to run it the script fails to run again.
If you have any idea of what the issue might be please let me know

**Comment by qazbnm456** [comment]
@jonchristmas Hey there, thanks for trying out! Though the tool is currently under inactive development, I'll still take some time to figure out the problem and give you the suggestion if there has one.

**Comment by qazbnm456** [comment]
Since `watchdog` has been under inactive development for a while, I decide to remove it and look for another replacement in the future.

Thus, you may clone project again with the latest commit and see if it works. I'll open the issue again if you've found another problem.
